### ISSUE TITLE
Translations & Reverse foreign keys during migrations

### ISSUE THREAD

**Issue by eugened19** [KristianOellegaard/django-hvad#301] opened 2016-06-17 23:26 UTC
Hi guys,

I've noticed strange pattern in my app

For one of the tasks, I need to retrieve reverse foreign key relations 
I use get_all_related_objects function from meta api

example:
SomeModel._meta.get_all_related_objects()

What I noticed is:
In case a model does not have translations associated with it, the function works fine and returns all foreign keys objects 
In case a model has translations associated with it, the function returns only a translation object, but no other ones even if they are defined in model and their related_name fields are present when I call dir(SomeModel).

Please help me with that
Please tell me if you need more info

Thank you!
Eugene

**Comment by spectras** [comment] 2016-06-18 04:52
Hello,

What version of Django are you using? `get_all_related_objects` is an internal Django API that has changed several times. Actually, it is deprecated in 1.9 and will be removed soon.
Django transition documentation recommends using this instead:

```python
[
    f for f in MyModel._meta.get_fields()
    if (f.one_to_many or f.one_to_one) and f.auto_created
]
```

It could help with your issue as, normally, all fields should be in `get_fields`, and from that point is should be easy to narrow down which fields pass and fail the filter and why.

**Comment by eugened19** [comment] 2016-06-18 15:06
Tried it your way

Still exactly kinda the same problem

If there is a translation in in a  model, get_fields() do not return foreign key fields except of a translation itself
If no translation present, everything is ok

django 1.8, django-hvad 1.5.0

**Comment by spectras** [comment] 2016-06-18 16:25
I am struggling to reproduce the issue. For instance, I built this small sample case:

```python
class Related(TranslatableModel):
    regular_field = models.CharField(max_length=50)
    translations = TranslatedFields(
        trans_field = models.CharField(max_length=50),
    )

class RelatedRelated(TranslatableModel):
    related = models.ForeignKey(Related, related_name='related_related', null=True)
    translated_fields = TranslatedFields(
        trans_related = models.ForeignKey(Related, related_name='related_trans_related', null=True),
    )
```

Now, when I run this…
```python
>>> Related._meta.get_all_related_objects()
[<ManyToOneRel: app.relatedtranslation>, <ManyToOneRel: app.relatedrelatedtranslation>, <ManyToOneRel: app.relatedrelated>]
```

Which is the expected output. We have the two foreign keys from `RelatedRelated` that, as we see, come from the shared and the translation model, and the translation model backing `Related` itself.

So I'm a bit stuck. Could you provide me with a sample test case that exhibits this behavior?

**Comment by eugened19** [comment] 2016-06-18 16:55
oh, sorry
I forgot to mention I'm running it in migration code
maybe it influences somehow?

**Comment by spectras** [comment] 2016-06-18 17:09
Well, I don't know the internals of Django ORM well enough, but Django's documentation says you must not import models in migration code, but use `apps.get_model("yourappname", "ModelName")` instead.

It will then use a frozen version of the model. I don't know how it is generated today. Back when it was still in South, only the models explicitly frozen were included, thus you would not see models from other apps in your migration.

**Comment by eugened19** [comment] 2016-06-18 17:18
In my case models are from the same app.And they are properly retrieved (not imported)

Can you please try this case yourself? If it works for you, I'll rest my case and will try different approach.

Thank you!

**Comment by spectras** [comment] 2016-06-18 18:17
Hmmm, during migrations, *hvad* is not loaded at all. It just generates the translations models but does not enable any of its mechanisms. This is so the migration sees the real underlying models (MyModel and MyModelTranslations) and processes them correctly.

It's really odd actually, I did try to look at migrations from a bigger project of mine, and it turns out sometimes fields are missing in `Model._meta.local_fields` (which is where `get_all_related_objects()` finds the fields eventually). On both translated and regular models.

That leads to an interesting question though : how does Django freeze and restore past versions of the models?

**Comment by eugened19** [comment] 2016-06-19 00:18
ok, so looks like this is not hvad specific problem
Thanks for clarifying!

**Comment by spectras** [comment] 2016-06-19 06:53
It is hard to know, it may still be though I do not understand how. The internals of the migrations API are pretty complex and not that well documented. In addition, they changed a lot over the last 3 versions of Django.

It's almost a small miracle that we managed to make hvad compatible with all three, but I don't understand well to what extent regular model manipulations can propagate into migration's `ModelState` class and what the consequences on the fake models it generates on the fly are.

Django migrations lack a proper API to enable third-party modules to customize that, and more than one module has to monkey-patch some stuff in there. Hopefully that will be addressed eventually.

**Comment by spectras** [comment] 2017-02-08 19:25
Since regular, non-hvad models exhibit the same behavior, I will tentatively close this issue for now.
Feel free to open again if required.

**Closed by spectras** 2017-02-08 19:25 UTC
