### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by cholpona** [KristianOellegaard/django-hvad#291] opened 2016-05-09 07:48 UTC
Hi,
We are using hvad in our project(python 2.7.6) and having some troubles when deleting translations in locale other than English(language of the django-admin). For example, when we are using Django-admin in Russian and try to delete any of the translations we get error : UnicodeDecodeError at /ru/admin/...... 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128) 
The problem came up in hvad/admin.py in line 243:
obj_display = '%s translation of %s' % (lang, force_text(obj.master))

Is there a smart solution for this problem? We have came up with 2 solutions, but all of them seems like not a smart solution:
1) to change the line to by explicitly telling that it is unicode -> obj_display = u'%s translation of %s' % (lang, force_text(obj.master))
2) to remove force_text from where the problem occurs -> obj_display = '%s translation of %s' % (lang, (obj.master))

I am including __unicode__ of the model being deleted in case we have messed up there:
def __unicode__(self):
        return (self.safe_translation_getter('name', str(self.name)))

**Comment by spectras** [comment] 2016-05-09 10:32
Hello,
Thanks for reporting. You are correct, several strings in `admin.py` lack the unicode marker for python2 (so that's solution number 1 for the problem). You may also want to check your `LANGUAGES` setting, it should have the language names marked as unicode as well. For instance:
```python
from django.utils.translation import ugettext_lazy as _l
LANGUAGES=(
    ('en', _l(u'English')),
    ('ru', _l(u'Russian')),
)
```
But anyway, as soon as the translated version of the language name is not ascii-compatible, line 243 will break. I have to fix it.

**Comment by spectras** [comment] 2016-05-09 10:39
Alright, the bug should be fixed on my local copy. Unfortunately I am using a connection in a café and ssh traffic is blocked, so I cannot push my changes. I'll do it as soon as I find an unblocked connection.

**Comment by spectras** [comment] 2016-05-13 18:04
Should be fixed on master I believe.

**Comment by cholpona** [comment] 2016-05-18 08:18
Thanks for fixing. Will it be included on the next release? If yes when the next release will be available?

**Comment by spectras** [comment] 2016-05-20 11:11
It will. I have no plan for releasing right now (not enough significant changes). But if you need it, I guess I can easily backport it to current release and release a 1.5.1.

**Comment by spectras** [comment] 2016-05-23 10:13
Done.
Closing now, but feel free to re-open if you encounter any issue.

**Closed by spectras** 2016-05-23 10:13 UTC
Labels: bug

**Comment by cholpona** [comment] 2016-05-30 11:56
Hi,
Is it still possible to release  1.5.1, we need that release :)

**Comment by spectras** [comment] 2016-05-30 16:30
You don't see it? I released it a week ago, and it correctly appears on pypi: https://pypi.python.org/pypi/django-hvad/1.5.1
Or did you upgrade yet the issue is still present?
