### ISSUE TITLE
TranslatableAdmin select only translated models

### ISSUE THREAD

**Issue by j-san** [KristianOellegaard/django-hvad#322] opened 2016-12-01 15:33 UTC
Is there any reason for TranslatableAdmin to list only translated models ? Also it looks like (but not tested) that with django < 1.9 there is a different behaviour ?

https://github.com/KristianOellegaard/django-hvad/blob/master/hvad/admin.py#L334

Maybe I've missed somethings, thank you for help 👍

**Comment by spectras** [comment] 2016-12-01 20:44
Hello!
This is the intended behavior, it was changed in [hvad 1.4.0](https://django-hvad.readthedocs.io/en/latest/public/release_notes.html#id3). The exact reasons are deep changes in Django ORM in version 1.9, preventing `FallbackQueryset.use_fallbacks()` from working at all on this version (and newer).
This forced hvad to push a change that had long been delayed, that is, dropping the inefficient `FallbackQueryset` in favor of adding a much faster JOIN clause to queries. This has the side-effect of hiding models that have no translation at all.

Such models have always been considered errors anyway (older hvad versions show them, but log an error everytime one is encountered). And hvad2 will prevent them altogether.

I am actually wondering how you create them (admin should not let you create them for instance), and what you use them for?

**Comment by j-san** [comment] 2016-12-02 08:37
In my case (only one model on my db), this model has untranslated representative fields and some optional translatable fields. Instances are created with Django Rest Framework through  `TranslatableModelSerializer`. In most case they are created without translations has long has optional fields are not requested to user.

This instances are no more listed in django admin since Django upgrade. I override get_queryset() on `TranslatableAdmin` to get all instances.

**Comment by spectras** [comment] 2016-12-02 09:20
Interesting. I guess that's something that should be addressed at the `TranslatableModelSerializer` level then, it should not create untranslated instances, but always create at least an instance in current or default language, even if its fields are empty.

I see where this happens. When `update()`-ing models, it always ensure a translation exists, creating it if it is missing. But for initial `create()`-ion, it relies on the default behavior, assuming there will always be at least one translated field or a language_code.
But, if using the form in non-_enforce_ mode, this may be incorrect.

I will look into it. In the meantime, I suggest you force a language on the serializer, by either of the following means:
  * Pass it a specific language to use when instanciating it. All models will be in that language.
  * Pass it `language=None` when instanciating it. This will force using detected browser language.
  * Have your javascript always specifiy a `language_code` field when creating a model.

Overriding `get_queryset` will work too, but will leave the instances untranslated, which will be a problem in the long run. By the way, if you need help adding default translations back to models that have none right now, just tell.

**Comment by sonic182** [comment] 2016-12-28 10:00
There is a way to set language to records added before installing django-havd on my app? I know I just could do a forloop with django shell but  something like a task `python manage.py havdupdatelanguages` would be great to have.

Also It should be said in django-havd admin documentation about old records without language will not be displayed in admin.

**Comment by spectras** [comment] 2016-12-29 10:38
Hello! I'm on holidays accessing github from my phone. This very question was discussed in a recent issue I believe. I can find it when I come back if you want.

**Comment by daesu** [comment] 2017-02-16 06:38
Hello, hope it's not too late to comment on this issue. 

I also have hit this issue and I want to make old records visible from before installing hvad. What's the 
best way to go about this ? 

Thanks

**Comment by spectras** [comment] 2017-02-16 11:46
@daesu> Hello. Please open new issues for new questions :)
I created issue #330 for you. Please see my answer over there.

**Closed** 2017-04-28 15:37 UTC
Labels: bug, help
