### ISSUE TITLE
Delete 1 translation instance from DRF.

### ISSUE THREAD

**Issue by alfredrumss** [KristianOellegaard/django-hvad#342] opened 2017-08-18 04:04 UTC
Hello, I'm using the DRF implementation, but how do I delete 1 translation from a request on DRF?.

I'm trying to do something like "../resource/:id?language=fr"   but it does not work because it deletes the main instance, I mean everything (the Shared Model).

the [doc](http://django-hvad.readthedocs.io/en/latest/public/queryset.html?highlight=delete#delete_translations)  and this [issue](https://github.com/KristianOellegaard/django-hvad/issues/274)  explain making it manually but I think maybe would exist some way to do it automatically but I don't know.

I think a workaround would be override the destroy method on the ModelViewSet.

**Comment by spectras** [comment] 2017-08-18 07:00
Hello,
The fundamental idea behind DRF implementation is as follows: either the endpoint is translation-aware, or not.

* If it is translation-aware, that is, it uses `TranslationsMixin` and exposes a dictionary of translations, then creating and deleting translations is done using a `PUT` request. Translations that are absent from the dictionary will be deleted, and new translations will be added.
* If it is not translation-aware, that is, it uses `TranslatableModelSerializer`, then, by design, it does not view the translations but just a single object, the fields of which happen to change depending on current language. Therefore, deleting the object deletes the main instance. In that case, there is no way to manage translations (neither add one nor delete one).

If you want to be able to delete a single translation, then it means your client code is translation-aware. In that case, you should probably expose the full dictionary with `TranslationsMixin`. That will be more reliable than trying to trick a fundamentally translation-unaware endpoint into beint somewhat aware of them, and you get better performance as you can update all object's translations in a single request.

**Comment by spectras** [comment] 2017-09-18 13:23
Closing as I believe the question was answered. Thanks for asking, and please feel free to re-open if you need to :)

**Closed by spectras** 2017-09-18 13:23 UTC
Labels: help

**Comment by alfredrumss** [comment] 2017-09-18 17:26
@spectras  yes, of course. Thanks for your answer.
